---
stages:
- name: Deploy VPN
  properties:
  - name: CUSTOMER_GATEWAY_IP
    value: ''
    type: text
  - name: CUSTOMER_SUBNET
    value: ''
    type: text
  - name: CUSTOMER_PSK
    type: secure
  jobs:
  - name: Deploy VPN
    type: deployer
    target:
      region_id: ibm:yp:us-south
      organization: cent@us.ibm.com
      space: jkwong-dev
      application: Deploy VPN
    script: |+
      #!/bin/bash

      if [ -z "${CUSTOMER_GATEWAY_IP}" -o \
           -z "${CUSTOMER_SUBNET}" -o \
           -z "${CUSTOMER_PSK}" ]; then
          echo "Must define three properties: CUSTOMER_GATEWAY_IP, CUSTOMER_SUBNET, CUSTOMER_PSK"
          exit 0
      fi

      oauth_token=`echo ${TOOLCHAIN_TOKEN} | awk '{print $2;}'`
      space_guid=${CF_SPACE_ID}

      echo "OAuth token=${oauth_token}"
      echo "Space guid=${space_guid}"

      vpn_service_name=`cf services | grep VPN_Service_Broker | awk '{ print $1; }'`

      if [ -z ${vpn_service_name} ]; then
        echo "Creating VPN Service for space ..."
        cf create-service VPN_Service_Broker Standard "VPN_${CF_SPACE}"
      fi

      gateways_json=`curl -X GET \
      -H "accept: application/json" \
      -H "content-type: application/json" \
      -H "x-auth-project-id: ${space_guid}" \
      -H "x-auth-token: ${oauth_token}" \
      https://containers-api.ng.bluemix.net/v3/vpns/gateways`

      echo ${gateways_json}
      num_gateways=`echo "${gateways_json}" | python -c "import sys,json; obj=json.load(sys.stdin); print len(obj['gateways'])"`

      if [ "${num_gateways}" == "0" ]; then
        echo "Creating gateway \"my-gateway\" ..."
        curl -X POST \
      -H "accept: application/json" \
      -H "content-type: application/json" \
      -H "x-auth-project-id: ${space_guid}" \
      -H "x-auth-token: ${oauth_token}" \
      -d "{ \"name\": \"my-gateway\", \"type\": \"allContainers\" }" \
      https://containers-api.ng.bluemix.net/v3/vpns/gateways
      fi

      connections_json=`curl -X GET \
      -H "accept: application/json" \
      -H "content-type: application/json" \
      -H "x-auth-project-id: ${space_guid}" \
      -H "x-auth-token: ${oauth_token}" \
      https://containers-api.ng.bluemix.net/v3/vpns/connections`

      #echo ${connections_json}

      num_connections=`echo "${connections_json}" | python -c "import sys,json; obj=json.load(sys.stdin); print len(obj['connections'])"`

      echo "num connections found=${num_connections}"
      FOUND=false

      for i in `seq 0 $((num_connections - 1))`; do
        gateway_ip=`echo "${connections_json}" | python -c "import sys,json; obj=json.load(sys.stdin); print obj['connections'][${i}]['customer_gateway']"`

        if [ "${gateway_ip}" == "${CUSTOMER_GATEWAY_IP}" ]; then
            FOUND=true
            break
        fi
      done

      if [ "${FOUND}" == "true" ]; then
        echo "connection to gateway ${CUSTOMER_GATEWAY_IP} exists!"
        exit 0
      fi

      # create the connection
      echo "Creating connection to gateway at ${CUSTOMER_GATEWAY_IP}"
      curl -X POST \
      -H "accept: application/json" \
      -H "content-type: application/json" \
      -H "x-auth-project-id: ${space_guid}" \
      -H "x-auth-token: ${oauth_token}" \
      -d "{ \"ikepolicy_name\": \"default\", \"ipsecpolicy_name\": \"default\", \"gateway_name\": \"my-gateway\", \"psk\": \"${CUSTOMER_PSK}\", \"customer_gateway\": \"${CUSTOMER_GATEWAY_IP}\",  \"customer_subnets\": [ \"${CUSTOMER_SUBNET}\" ], \"name\": \"connection\" }" \
      https://containers-api.ng.bluemix.net/v3/vpns/connections

hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
